### PR TITLE
fix tree agglomeration in agglomerateByPrevalence

### LINKED ISSUE #573: agglomerateByPrevalence does not return rowTree
`agglomerateByPrevalence` returns a TSE object without rowTree, no matter the value of the `agglomerate.tree` argument.

```
library(mia)
data("GlobalPatterns")
tse <- GlobalPatterns
tse <- agglomerateByPrevalence(tse, rank = "Phylum", agglomerate.tree = TRUE)
rowTree(tse)
```
>NULL

```
library(mia)
data("GlobalPatterns")
tse <- GlobalPatterns
tse <- agglomerateByPrevalence(tse, rank = "Phylum", agglomerate.tree = FALSE)
rowTree(tse)
```
>NULL

It should return a TSE object with its rowTree, agglomerated or not depending on the `agglomerate.tree` argument.

It is worth nothing that the `agglomerateByRank` function works correctly and returns a TSE object with its rowTree:
```
library(mia)
data("GlobalPatterns")
tse <- GlobalPatterns
tse <- agglomerateByRank(tse, rank = "Phylum", agglomerate.tree = TRUE)
rowTree(tse)
```
>Phylogenetic tree with 67 tips and 66 internal nodes.
Tip labels:
  549322, 173903, 368907, 51888, 591769, 249529, ...
Node labels:
  , 0.858.4, 1.000.21479, 0.946.619, 0.953.588, 0.940.473, ...
Rooted; includes branch lengths.

### PR DESCRIPTION
**Pull request by theotimeee**
As mentioned in https://github.com/microbiome/mia/issues/573, agglomerateByPrevalence returns a TSE object with `rowTree = NULL`.

This PR removes the class checking and class conversion from TSE to SCE that removes the tree.

With this modification, the tree is returned and agglomerated if `agglomerate.tree = TRUE`.

```
data("GlobalPatterns")
tse <- GlobalPatterns
tse <- agglomerateByPrevalence(tse, rank = "Phylum", agglomerate.tree = FALSE)
rowTree(tse)
```
>Phylogenetic tree with 19216 tips and 19215 internal nodes.
>Tip labels:
  549322, 522457, 951, 244423, 586076, 246140, ...
Node labels:
  , 0.858.4, 1.000.154, 0.764.3, 0.995.2, 1.000.2, ...
>Rooted; includes branch lengths.

```
data("GlobalPatterns")
tse <- GlobalPatterns
tse <- agglomerateByPrevalence(tse, rank = "Phylum", agglomerate.tree = TRUE)
rowTree(tse)
```
>Phylogenetic tree with 67 tips and 66 internal nodes.
Tip labels:
  549322, 173903, 368907, 51888, 591769, 249529, ...
Node labels:
  , 0.858.4, 1.000.21479, 0.946.619, 0.953.588, 0.940.473, ...
Rooted; includes branch lengths.

### CODE REVIEW

**Review by TuomasBorman — APPROVED** [review]

**Review by TuomasBorman — CHANGES_REQUESTED** [review]
Can you add unit tests?

I found also that the tree does not correspond to rows of TreeSE. There are more tips in tree than there are rows. This is because the agglomeration is done in agglomerateByRank and then after rank agglomeration, agglomeratio is done by prevalence. However, user would expect that the agglomeration of tree is also done by prevalence. --> add tree agglomeration also in agglomerateByPrevalence

File: R/getPrevalence.R [hunk 1]
```diff
@@ -580,18 +586,11 @@ setMethod("agglomerateByPrevalence", signature = c(x = "SummarizedExperiment"),
...
-                class <- "SingleCellExperiment"
-            } else {
-                class <- class[class_x == class]
-            }
-            x <- rbind(as(x[f,],class),
-                       as(other_x,class))
-            x <- as(x,class_x)
+            x <- rbind(x[f,], other_x)
+        }
+        if (agglomerate.tree == TRUE){
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: `if( agglomerate.tree )`

**Review by TuomasBorman — CHANGES_REQUESTED** [review]
Minor fix.

Add also news and version bump

**Comment by TuomasBorman** [comment]
Also add input check for agglomerate.tree. Fail fast.

File: R/getPrevalence.R (hunk 1 above)
Comment (TuomasBorman) [reply R/getPrevalence.R]: This was not addressed. As agglomerate.tree is already boolean, it is good practice to use it directly instead of comparing boolean value to boolean value

**Comment by TuomasBorman** [comment]
Realized one thing: the function might not work if the input is SummarizedExperiment since it has no trees.

--> Create generic method for TreeSummarizedExperiment
1. Call next method which will can generic SE method
2. Merge trees
3. Merge reference sequences (see agglomerateByVariable)

File: R/getPrevalence.R [hunk 2]
```diff
@@ -580,19 +590,42 @@ setMethod("agglomerateByPrevalence", signature = c(x = "SummarizedExperiment"),
...
+        stop("'mergeRefSeq' must be TRUE or FALSE.", call. = FALSE)
+      }
+      # for optionally merging referenceSeq
+      f <- rownames(x) 
+      refSeq <- NULL
+      if(mergeRefSeq){
+        refSeq <- referenceSeq(x)
+      }
+      #
+      x <- .merge_rows(x, f, archetype = 1L, ...)
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: Wondering what is the .merge_rows doing here.

I think this line should be the callNextMethod() call

Comment (TuomasBorman) [reply R/getPrevalence.R]: This merges rows with rownames --> this does not do anything?

File: R/getPrevalence.R [hunk 3]
```diff
@@ -580,19 +590,42 @@ setMethod("agglomerateByPrevalence", signature = c(x = "SummarizedExperiment"),
...
+      # optionally merge rowTree
+      if( agglomerate.tree ){
+        x <- .agglomerate_trees(x, 1)
+      }
+      # optionally merge referenceSeq
+      if(!is.null(refSeq)){
+        referenceSeq(x) <- .merge_refseq_list(refSeq, f, rownames(x), ...)
+      }
+      x
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: Use return(x)

File: R/getPrevalence.R (hunk 2 above)
Comment (theotimeee) [reply R/getPrevalence.R]: Yes I did not notice that, I removed it but I already call callNextMethod() at the beginning of the method, should I move it to this line?

File: R/getPrevalence.R [hunk 4]
```diff
@@ -517,7 +517,17 @@ setMethod("getPrevalentAbundance", signature = c(x = "SummarizedExperiment"),
...
+#'   
+#' @param agglomerate.tree \code{TRUE} or \code{FALSE}: should
+#'   \code{rowTree()} also be agglomerated? (Default:
+#'   \code{agglomerate.tree = FALSE})
+#'
+#' @param mergeRefSeq logical scalar: Should a consensus sequence be calculated?
+#' If set to \code{FALSE}, the result
+#' from \code{archetype} is returned; If set to \code{TRUE} the result
+#' from \code{\link[DECIPHER:ConsensusSequence]{DECIPHER::ConsensusSequence}}
+#' is returned. (Default: \code{mergeRefSeq = FALSE})
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: These will be changed by this PR https://github.com/microbiome/mia/pull/582 which takes the priority

File: R/getPrevalence.R (hunk 2 above)
Comment (TuomasBorman) [reply R/getPrevalence.R]: I did not check in detail, but in theory reference sequence might already be modified when calling callNextMethod(). That is because the SE method then calls other agglomeration methods.

That is why it might be safest to first take the reference sequences and then call callNextMethod() so that you have stored the original reference sequences.

Moreover, I realized that these all agglomeration functions are in same documentation page. agglomerateByVariable() can be done also in column-wise which means that it must have mergeRefSeq parameter as "hidden" parameter. --> agglomerateByPrevalence() should also have the parameter as hidden (in "...")

Comment (TuomasBorman) [reply R/getPrevalence.R]: You could do it with `list(...)[["mergeRefSeq"]]` without creating an internal function. Just explain in code comment, why this is done that way

File: R/getPrevalence.R [hunk 5]
```diff
@@ -601,30 +595,34 @@ setMethod("agglomerateByPrevalence", signature = c(x = "SummarizedExperiment"),
...
       refSeq <- NULL
-      if(mergeRefSeq){
-        refSeq <- referenceSeq(x)
+      # mergeRefSeq is a hidden parameter as for all other agglomeration methods
+      # from the agglomerate-methods man page.
+      # Here 'list(...)[["mergeRefSeq]]' is used to access it.
+      if( "mergeRefSeq" %in% names(list(...)) && 
+          !(is.null(list(...)[["mergeRefSeq"]]) || 
+            .is_a_bool(list(...)[["mergeRefSeq"]])) ){
+        stop("'mergeRefSeq' must be TRUE or FALSE.", call. = FALSE)
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: To make this more readable, get the value first to variable and then use it

**Review by TuomasBorman — CHANGES_REQUESTED** [review]
Looks good

File: R/getPrevalence.R [hunk 6]
```diff
@@ -580,19 +584,46 @@ setMethod("agglomerateByPrevalence", signature = c(x = "SummarizedExperiment"),
...
+      # for optionally merging referenceSeq
+      f <- rownames(x) 
+      refSeq <- NULL
+      # mergeRefSeq is a hidden parameter as for all other agglomeration methods
+      # from the agglomerate-methods man page.
+      # Here 'list(...)[["mergeRefSeq]]' is used to access it.
+      mergeRefSeq <- list(...)[["mergeRefSeq"]]
+      if( "mergeRefSeq" %in% names(list(...)) && 
+          !(is.null(mergeRefSeq) || 
+            .is_a_bool(mergeRefSeq)) ){
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: It is enough to test

```
merge_refseq <- list(...)[["update.refseq"]]
!is.null(merge_refseq) && !.is_a_bool(merge_refseq)
```

If that parameter is not available the value is NULL. If the value is not NULL and not boolean, it should lead to error.

File: R/getPrevalence.R [hunk 7]
```diff
@@ -580,19 +584,46 @@ setMethod("agglomerateByPrevalence", signature = c(x = "SummarizedExperiment"),
...
+        stop("'mergeRefSeq' must be TRUE or FALSE.", call. = FALSE)
+      }
+      else if( "mergeRefSeq" %in% names(list(...)) ){
+        refSeq <- referenceSeq(x)
+      }
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: Then this could be

if( !is.null(merge_refseq) && merge_refseq ){
    refSeq <- referenceSeq(x)
}

File: R/getPrevalence.R (hunk 6 above)
Comment (TuomasBorman) [reply R/getPrevalence.R]: Let's get back to drawing board, this is too complex.

```
merge_refseq <- list(...)[["update.refseq"]]
if( is.null(merge_refseq) {
merge_refseq <- FALSE
}
if( !.is_a_bool(merge_refseq) ){
error
}
if( merge_refseq ){
refSeq <- referenceSeq(x)
}
....
...
...

if( merge_refseq ){
referenceSeq(x) <- .merge_refseq_list(refSeq, f, rownames(x), ...)
}
```

File: R/getPrevalence.R (hunk 7 above)
Comment (TuomasBorman) [reply R/getPrevalence.R]: This comment is outdated.

File: R/getPrevalence.R [hunk 8]
```diff
@@ -590,19 +594,46 @@ setMethod("agglomerateByPrevalence", signature = c(x = "SummarizedExperiment"),
...
+      if( !.is_a_bool(merge_refseq) ){
+        stop("'update.refseq' must be TRUE or FALSE.", call. = FALSE)
+      }
+      if( merge_refseq ){
+        refSeq <- referenceSeq(x)
+      }
+      if( merge_refseq ){
+        referenceSeq(x) <- .merge_refseq_list(refSeq, f, rownames(x), ...)
+      }
+      x <- callNextMethod()
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: You should probably first call

x <- callNextMethod()

and then

 if( merge_refseq ){
        referenceSeq(x) <- .merge_refseq_list(refSeq, f, rownames(x), ...)
 }
 
 I have not tested the code yet, but it looks like it

**Comment by TuomasBorman** [comment]
Agglomeration of reference sequences was not working, but now everything should be fine.

Can you add tests for reference sequences? Check other agglomeration functions and their unit tests.

You can find suitable data from data("SilvermanAGutData", package = "miaTime")

File: R/getPrevalence.R [hunk 9]
```diff
@@ -638,7 +638,7 @@ setMethod("agglomerateByPrevalence",
         }
         # Update tree if user has specified to do so
         if( update.tree ){
-            res <- .agglomerate_trees(res, 1)
+          res <- .agglomerate_trees(res, 1)
```
Comment (TuomasBorman) [inline R/getPrevalence.R]: Indentation off

File: tests/testthat/test-5prevalence.R [hunk 10]
```diff
@@ -452,7 +452,7 @@ test_that("agglomerateByPrevalence", {
       seqs_ref, factor(rep(feature, length(seqs_ref))), rownames(seqs_ref),
       threshold = th)
     seqs_test <- seqs_test[ names(seqs_test) %in% feature ]
-    expect_equal(seqs_test, seqs_ref)
+    expect_equal(seqs_test, seqs_ref, tolerance = 10**-2)
```
Comment (TuomasBorman) [inline tests/testthat/test-5prevalence.R]: Explain with the comment why there is tolerance (the tolerance is also quite high)

Comment (theotimeee) [reply tests/testthat/test-5prevalence.R]: Actually after modification tolerance is not needed

**Review by TuomasBorman — APPROVED** [review]
Cool!
