### PR TITLE
Multiple row/colTrees: fix functions

### LINKED ISSUE #286: rowTree can store multiple trees, this is not taken into account currently
`rowTree` and `colTree` slots can store multiple trees. Our methods do not take this into account. For example, `estimateFaith` takes just the first tree. 

I suggest to add `whichTree` argument. This takes character values that specify the `rowTree`. 

`tree <- rowTree(tse, "phylo")`

After that, the `tse` is subsetted based on `rowTree`. (Take only those rows that are present in tree.) The faith index is calculated based on subsetted data. 

Also other functions should be checked. Probably we can have similar functionality in those

### PR DESCRIPTION
**Pull request by TuomasBorman**
https://github.com/microbiome/mia/issues/286

### CODE REVIEW

File: R/runDPCoA.R [hunk 1]
```diff
@@ -141,11 +139,27 @@ setMethod("calculateDPCoA", c("ANY","ANY"), .calculate_dpcoa)
 #' @rdname runDPCoA
 setMethod("calculateDPCoA", signature = c("TreeSummarizedExperiment","missing"),
     function(x, ..., assay_name = abund_values, abund_values = exprs_values, 
-             exprs_values = "counts", dimred = NULL, n_dimred = NULL)
```
Comment (TuomasBorman) [inline R/runDPCoA.R:144]: dimred and n_dimred were not used

File: R/runDPCoA.R [hunk 2]
```diff
@@ -141,11 +139,27 @@ setMethod("calculateDPCoA", c("ANY","ANY"), .calculate_dpcoa)
...
+        #
+        # Get tree
+        tree <- rowTree(x, tree_name)
+        # Select only those features that are in the rowTree
+        whichTree <- rowLinks(x)[ , "whichTree"] == tree_name
+        if( any(!whichTree) ){
+            warning("Not all rows were present in the rowTree specified by 'tree_name'.",
+                    "'x' is subsetted.", call. = FALSE)
+            # Subset the data
+            x <- x[ whichTree, ]
```
Comment (TuomasBorman) [inline R/runDPCoA.R:158]: It might be that the rowTree(x, "something") does not include all the rows (rowTree(x, "another") has those) --> the data is subsetted to match the tree

File: tests/testthat/test-5runDPCoA.R [hunk 3]
```diff
@@ -11,4 +11,57 @@ test_that("runDPCoA", {
...
+    # )
+    # expect_error(
+    #     runDPCoA(esophagus, name = 1, assay_name = "counts", tree_name = "phylo", ncomponents = 1.3, ntop = "test",
+    #              subset_row = NULL, scale = FALSE, transposed = FALSE)
+    # )
+    
+    data("GlobalPatterns")
+    tse <- mergeSEs(esophagus, GlobalPatterns)
+    # expect_warning(runDPCoA(tse))
+    # expect_warning(runDPCoA(tse, tree_name = "phylo.1"))
```
Comment (TuomasBorman) [inline tests/testthat/test-5runDPCoA.R:66]: https://github.com/microbiome/mia/pull/300

**Comment by TuomasBorman** [comment]
I'm not sure where this comes from; I'm not able to reproduce it


https://github.com/microbiome/mia/runs/7951632999?check_suite_focus=true#step:20:262

**Comment by antagomir** [comment]
I do not immediately recognize the source either... what should we do about it? If it works otherwise well.

**Comment by TuomasBorman** [comment]
The error occurs here https://github.com/vegandevs/vegan/blob/fab100aa42dd10c1a780f654b6718926ff556d3b/R/ordConstrained.R#L357

Not 100% sure, but it looks that the `if `is not as strict as it should be

E: Though I'm not able to reproduce any examples. As the test should now work (Primer variable replaced with shannon) and we kind of know what causes this, I think we can ignore this (This should be very rare case, but it might be good to inform vegandevs about this)

**Comment by TuomasBorman** [comment]
Good? This should be merged next

**Comment by antagomir** [comment]
good as far as I can see - !
