### PR TITLE
getPrevalence, NA values

### LINKED ISSUE #492: getPrevalence, named numeric(0) if NA values in the assay
**Describe the bug**
If there are NA values in the assay, `getPrevalence()` returns `named numeric(0)` instead of prevalence table

**To Reproduce**
```R
library(miaTime)
library(mia)
data(hitchip1006)
tse <- hitchip1006

# Add NA values to matrix
assay(tse, "counts")[, "Sample-1"] <- NA
assay(tse, "counts")[, "Sample-3"] <- NA

prevalent_family <- getPrevalence(tse, detection = 10 / 100,
                   sort = TRUE, assay.type = "counts",
                   as_relative = TRUE")

prevalent_family
#> named numeric(0)
```

On a different dataset this problem was solved by specifying the `rank` argument in `getPrevalence` but it does not work in this case.

```R
library(miaTime)
library(mia)
data(hitchip1006)
tse <- hitchip1006

# Add NA values to matrix
assay(tse, "counts")[, "Sample-1"] <- NA
assay(tse, "counts")[, "Sample-3"] <- NA

prevalent_family <- getPrevalence(tse, detection = 10 / 100,
                   sort = TRUE, assay.type = "counts",
                   as_relative = TRUE,
                   rank = "Family") # Specifying rank does not solve the issue

prevalent_family
#> named numeric(0)
```

**Additional context**
Tested on the latest development mia version.

```
R Under development (unstable) (2024-01-09 r85796)
Platform: x86_64-pc-linux-gnu
Running under: Linux Mint 21.3

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Helsinki
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] mia_1.11.1                      MultiAssayExperiment_1.29.1    
 [3] TreeSummarizedExperiment_2.11.0 Biostrings_2.71.2              
 [5] XVector_0.43.1                  SingleCellExperiment_1.25.0    
 [7] SummarizedExperiment_1.33.3     Biobase_2.63.0                 
 [9] GenomicRanges_1.55.2            GenomeInfoDb_1.39.6            
[11] IRanges_2.37.1                  S4Vectors_0.41.3               
[13] BiocGenerics_0.49.1             MatrixGenerics_1.15.0          
[15] matrixStats_1.2.0               miaTime_0.1.21                 
[17] devtools_2.4.5                  usethis_2.2.2                  
[19] reprex_2.1.0                   

loaded via a namespace (and not attached):
  [1] rstudioapi_0.15.0           jsonlite_1.8.8             
  [3] magrittr_2.0.3              ggbeeswarm_0.7.2           
  [5] rmarkdown_2.25              fs_1.6.3                   
  [7] zlibbioc_1.49.0             vctrs_0.6.5                
  [9] memoise_2.0.1               DelayedMatrixStats_1.25.1  
 [11] RCurl_1.98-1.14             htmltools_0.5.7            
 [13] S4Arrays_1.3.3              curl_5.2.0                 
 [15] BiocNeighbors_1.21.2        SparseArray_1.3.4          
 [17] htmlwidgets_1.6.4           desc_1.4.3                 
 [19] plyr_1.8.9                  DECIPHER_2.31.2            
 [21] cachem_1.0.8                igraph_2.0.2               
 [23] mime_0.12                   lifecycle_1.0.4            
 [25] pkgconfig_2.0.3             rsvd_1.0.5                 
 [27] Matrix_1.6-4                R6_2.5.1                   
 [29] fastmap_1.1.1               GenomeInfoDbData_1.2.11    
 [31] shiny_1.8.0                 digest_0.6.34              
 [33] colorspace_2.1-0            ps_1.7.6                   
 [35] scater_1.31.2               irlba_2.3.5.1              
 [37] pkgload_1.3.4               vegan_2.6-4                
 [39] beachmat_2.19.1             fansi_1.0.6                
 [41] mgcv_1.9-1                  abind_1.4-5                
 [43] compiler_4.4.0              remotes_2.4.2.1            
 [45] withr_3.0.0                 BiocParallel_1.37.0        
 [47] viridis_0.6.5               DBI_1.2.1                  
 [49] pkgbuild_1.4.3              MASS_7.3-60.1              
 [51] DelayedArray_0.29.1         sessioninfo_1.2.2          
 [53] bluster_1.13.0              permute_0.9-7              
 [55] tools_4.4.0                 vipor_0.4.7                
 [57] beeswarm_0.4.0              ape_5.7-1                  
 [59] httpuv_1.6.14               clipr_0.8.0                
 [61] glue_1.7.0                  callr_3.7.3                
 [63] nlme_3.1-164                promises_1.2.1             
 [65] grid_4.4.0                  reshape2_1.4.4             
 [67] cluster_2.1.6               generics_0.1.3             
 [69] gtable_0.3.4                tidyr_1.3.1                
 [71] BiocSingular_1.19.0         ScaledMatrix_1.11.0        
 [73] utf8_1.2.4                  ggrepel_0.9.5              
 [75] pillar_1.9.0                stringr_1.5.1              
 [77] yulab.utils_0.1.4           later_1.3.2                
 [79] splines_4.4.0               dplyr_1.1.4                
 [81] treeio_1.27.0               lattice_0.22-5             
 [83] tidyselect_1.2.0            DirichletMultinomial_1.45.0
 [85] miniUI_0.1.1.1              scuttle_1.13.0             
 [87] knitr_1.45                  gridExtra_2.3              
 [89] xfun_0.42                   stringi_1.8.3              
 [91] yaml_2.3.8                  lazyeval_0.2.2             
 [93] evaluate_0.23               codetools_0.2-19           
 [95] tibble_3.2.1                BiocManager_1.30.22        
 [97] cli_3.6.2                   xtable_1.8-4               
 [99] munsell_0.5.0               processx_3.8.3             
[101] Rcpp_1.0.12                 parallel_4.4.0             
[103] ellipsis_0.3.2              ggplot2_3.4.4              
[105] profvis_0.3.8               urlchecker_1.0.1           
[107] sparseMatrixStats_1.15.0    bitops_1.0-7               
[109] decontam_1.23.0             viridisLite_0.4.2          
[111] tidytree_0.4.6              scales_1.3.0               
[113] purrr_1.0.2                 crayon_1.5.2               
[115] rlang_1.1.3              
```

### PR DESCRIPTION
**Pull request by TuomasBorman**
If there are NA values, they are interpreted as FALSE i.e., certain value do not exceed the detection threshold i.e. "this taxon cannot be found from this sample"

### CODE REVIEW

**Review by antagomir — APPROVED** [review]

**Review by antagomir — COMMENTED** [review]
This is good if we assume that users will always want to consider NA as "not detected". I think this is OK.

Another option would be to let users pass na.rm=TRUE for rowSums on line 216 (or perhaps this could be the default then; albeit now na.rm=FALSE by default in other parts of this R file).

It might be advisable to throw a warning when NAs are interpreted as "not detected". User should get to know this.

I would also add some unit tests to spot this problem in the future if anything is changed?

**Comment by TuomasBorman** [comment]
One option is to catch `na.rm` in `.agg_for_prevalence` function and create new parameter called `drop.empty.rank` --> don't feed it to `agglomreateByRank` function instead use `drop.empty.rank`


--> Use na.rm in rowSums in line 216

**Comment by antagomir** [comment]
Yes the `drop.empty.rank` might be more clear.

**Comment by antagomir** [comment]
TBH I am not sure how necessary it is to allow users decide whether they want to have to have `na.rm` TRUE of FALSE in the merging. But perhaps it is good to let user decide ultimately. 

I would pay some attention for documentation, examples & unit tests to keep it clear for users.

**Comment by TuomasBorman** [comment]
Is it now good to go?

File: R/getPrevalence.R [hunk 1]
```diff
@@ -34,12 +34,18 @@
...
+#' prevalence? (default: \code{na.rm = TRUE})
+#'   
 #' @param ... additional arguments
 #' \itemize{
 #'   \item{If \code{!is.null(rank)} arguments are passed on to
 #'     \code{\link[=agglomerate-methods]{agglomerateByRank}}. See
 #'     \code{\link[=agglomerate-methods]{?agglomerateByRank}} for more details.
+#'     Note that you can specify whether to remove empty ranks with
+#'     \code{drop.empty.ranks} instead of \code{na.rm}. (default:
+#'     \code{drop.empty.rank = FALSE})
```
Comment (antagomir) [inline R/getPrevalence.R]: should here be rank -> ranks?

Comment (antagomir) [reply R/getPrevalence.R]: or just "default: FALSE"

File: R/getPrevalence.R [hunk 2]
```diff
@@ -204,13 +213,13 @@ setMethod("getPrevalence", signature = c(x = "ANY"),
...
         #
-
         if (include_lowest) {
             prev <- x >= detection
         } else {
             prev <- x > detection
         }
-        prev <- rowSums(prev)
+        # Calculate prevalence for each taxa
+        prev <- rowSums(prev, na.rm = na.rm)
```
Comment (antagomir) [inline R/getPrevalence.R:229]: I am still just wondering if we should throw a warning in a case where NAs actually exist & actively ignored? (ignoring NAs is now the default, user might not notice that this happens unless they are warned)

File: tests/testthat/test-5prevalence.R [hunk 3]
```diff
@@ -62,6 +62,36 @@ test_that("getPrevalence", {
...
+    # Check that na.rm works correctly
+    tse <- GlobalPatterns
+    # Get reference value
+    ref <- getPrevalence(tse, assay.type = "counts")
+    # Add NA values to matrix
+    remove <- c(1, 3, 10)
+    assay(tse, "counts")[remove, ] <- NA
+    # There should be 3 NA values if na.rm = FALSE. Otherwise there should be 0
+    expect_true( sum(is.na(
+        getPrevalence(tse, assay.type = "counts", na.rm = FALSE) )) == 3)
```
Comment (antagomir) [inline tests/testthat/test-5prevalence.R]: does this also work when `rank` argument is specified? Because earlier there were differences how this works when rank is additionally provided, compared to this present example.

**Review by antagomir — COMMENTED** [review]
Some suggestions in the comments.

File: R/getPrevalence.R (hunk 1 above)
Comment (TuomasBorman) [reply R/getPrevalence.R]: The documentation is not unified; there are multiple forms in this file alone --> (default: something=FALSE), (default: FALSE)

--> FALSE

File: R/getPrevalence.R (hunk 2 above)
Comment (TuomasBorman) [reply R/getPrevalence.R:229]: That is good and adds transparency

File: tests/testthat/test-5prevalence.R (hunk 3 above)
Comment (TuomasBorman) [reply tests/testthat/test-5prevalence.R]: These modifications do not affect this thing, I guess. (I am not sure what differences there were)

When rank is specified

1. TreeSE is agglomerated to level specified by `rank`. `agg.na.rm` (I renamed `drop.empty.ranks`) is used to specify whether to drop those rows that do not have taxonomy in level specified by `rank.` --> Instead of "phylum_something" & "class_something2" there are only taxa that have taxonomy info in class level, for instance.

2. If there are NA values, agglomerated tables have also NA values in higher level rank --> This might be misleading? We could add parameter to agglomerateByRank that removes NAs? (agglomerateByRanks --> mergeRows --> .merge_rows --> scuttle::sumCountsAcrossFeatures)

3. getPrevalence calculates prevalence of features. With `na.rm,` user can specify whether to remove NA values.


So currently, when there are NA values and rank is specified, there are some taxa that have prevalence NA.

File: R/getPrevalence.R [hunk 4]
```diff
@@ -213,6 +212,14 @@ setMethod("getPrevalence", signature = c(x = "ANY"), function(
             stop("'sort' must be TRUE or FALSE.", call. = FALSE)
         }
         #
+        # Give warning if there are taxa with NA values
+        if( any( is.na(x) ) ){
+            msg <- paste0(
+                "The abundance table contains NA values and they are ",
+                ifelse(na.rm, "not", ""), "excluded (see 'na.rm').")
```
Comment (antagomir) [inline R/getPrevalence.R]: is this in sync with the agg.na.rm?

**Review by antagomir — COMMENTED** [review]
Can we also have in unit tests test of the rank parameter, something like

getPrevalence(tse, assay.type = "counts", na.rm = FALSE, rank="Genus")

File: R/getPrevalence.R (hunk 4 above)
Comment (TuomasBorman) [reply R/getPrevalence.R]: This is `na.rm` for `getPrevalence` function (`agg.na.rm` is for `agglomerateByRanks`) --> so yes

Comment (antagomir) [reply R/getPrevalence.R]: Ok. Just ensure it is sufficiently clear from documentation what na.rm is for what purposes and there is no real risk for confusion between those.
